### ISSUE TITLE
Time Travel for Estimate MYA Prices

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#102]
I took my Marquis Farm case and manually set the date to July 10th.    This date is prior to the July WASDE release.   On this date, estimated MYA prices at a 1.0 price factor should equal the June WASDE prices.   

June WASDE MYA was $4.80 for corn, $12.10 for Beans, and $7.70 for Wheat. 
July WASDE MYA is $4.80 for corn, $12.10 for beans and $7.70 for Wheat.    

What is showing up on the Title page for sensitized MYA are the July MYA numbers instead of the June MYA numbers.   I presume that those are what are driving the title payments calculations also.    

Like other time travel features of IFBT, if we set a prior date, ideally would be able to use the estimated MYA as of that date both to show the user on the Title page as well as to use for the Title payment calculations.

**Comment by KelleyDrake** [comment]
Correction:

June WASDE MYA was $4.80 for corn, $12.10 for Beans, and $7.70 for Wheat.
July WASDE MYA is $4.80 for corn, $12.40 for beans and $7.50 for Wheat.

**Comment by ddrake** [comment]
The reason for this is that the reference wasde_release_date for July is actually 2023-07-10.  This date is basically copied from simplebudgettool.MyaPrices.  We use *that* date in calculating the MYA price, not the *actual* date of the release.  To be sure you are catching the June MyaPrice, you need to set model_run_date to 7/9 or before.  This behavior is consistent with other updates, such as the RMA price and yield updates which use the dates in simplebudgettool "County Crop Types and Ins Dates" regardless of the actual release date.

 Because of this implementation detail, time travel is somewhat imprecise but has the advantage that the time traveler doesn't need to know the *actual* release dates, but only the *reference* dates.  On the other hand, to use the *actual* release dates instead, would require a major code re-write and would lead to performance issues, more uncertainty for the time traveler, and testing difficulties.
