### ISSUE TITLE
Minor Comment on the Revenue Section

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#105]
On Marquis Partners farm, you'll see that currently I am undersold on FS beans and oversold on DC beans.   It seems like since bushels are fungible, we'd rather see the both having a positive (undersold) amount or both having a negative (oversold) amount.   To do that I think we probably need to take the entirety of expected bean production (both FS and DC) and the entirety of contracted beans, calculate the percent remaining to be sold or oversold and then apply that % equally to expected production for each of FS and DC beans.  I think since DC beans have a much lower yield that might be causing the funny looking result.   The totals all look great and the new presentation is very good and important to the overall picture.   So very happy with it with that one minor exception.

**Comment by ddrake** [comment]
This should be working now.

I may be able to figure out how to put the per rented and per owned acres in their own box and ensure that the box stays centered under the planted acres, but I'm not really seeing how to do that.  I don't think there's a problem with four crops, because the label spans the first n-1 crop columns (see Marquis farm).  It even works ok (at least in my browser) if there's only one crop.

**Comment by KelleyDrake** [comment]
Ok.  Don't waste the time on that last fix.   All good!

**Comment by ddrake** [comment]
Closing as complete.
