### ISSUE TITLE
Suggestion for the Grain Marketing presentation to make clearer and simpler

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#152]
I like the new grain marketing page which combines futures and basis on one row.   I do have a relatively minor format change suggestion.   I have uploaded to IFBT share site a simple spreadsheet that shows for my Madison County Farm a presentation for the grain marketing that I think looks better, is clearer and easier to understand.    I don't think it would be hard to implement.    It will also allow more to fit on a single page and will look nicer.   Take a look on IFBT google share site for "Grain Marketing Presentation" and you can reference my Madison County Farm on IFBT as that is where the numbers are coming from.

**Comment by ddrake** [comment]
I'm not quite clear -- 
1. Are you referring to the PDF or the table on the MarketViewUpdate page?
2. You're not proposing that the user enter separately futures bushels and basis bushels, right?  I think you're saying that for display purposes we show the bushels column twice, with different headings, but the same information, because that simplifies the totals -- correct?

**Comment by ddrake** [comment]
Should be complete as of commit: e97f0ac
