### ISSUE TITLE
Price updates

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#153]
I noticed this morning that our harvest price for corn is $4.76.   Friday's 9/29 close was $4.7675 and yesterday's 10/2 close was $4.8875.
The date shown for the recent harvest price was 9/29.   So it looks like last night's price update did not take effect?

**Comment by ddrake** [comment]
Thanks for letting me know.  I’ll fix it soon.

Sent from my iPad

On Oct 3, 2023, at 7:42 AM, KelleyDrake ***@***.***> wrote:

﻿

I noticed this morning that our harvest price for corn is $4.76. Friday's 9/29 close was $4.7675 and yesterday's 10/2 close was $4.8875.
The date shown for the recent harvest price was 9/29. So it looks like last night's price update did not take effect?

**Comment by KelleyDrake** [comment]
Also, Ideally we would get the actual closing price.  Revisiting a prior issue, I think we are still getting the post close price in the 15 minutes of late trading.   If it would be possible to get the actual close that would be better.    But if that is not possible we can continue to use that "almost closing price".   Since you are now 100% barchart does that open up the possibility of a rebook at that question that arose before?  And is there an easy way to get to the exact published closing price?   No big deal if not easy...but thought I'd ask.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/3/23 9:44 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Price updates (Issue #153)


Thanks for letting me know. I’ll fix it soon.

Sent from my iPad

On Oct 3, 2023, at 7:42 AM, KelleyDrake ***@***.***> wrote:

﻿

I noticed this morning that our harvest price for corn is $4.76. Friday's 9/29 close was $4.7675 and yesterday's 10/2 close was $4.8875.
The date shown for the recent harvest price was 9/29. So it looks like last night's price update did not take effect?

**Comment by ddrake** [comment]
No, the live server isn’t using the barchart script yet.  I wanted to test it on my local machine first, but couldn’t do that until last night.  I did do some work over the weekend on the live server scripts to enable email notifications.  That’s most likely what broke the script this morning.

Sent from my iPad

On Oct 3, 2023, at 7:54 AM, KelleyDrake ***@***.***> wrote:

﻿

Also, Ideally we would get the actual closing price. Revisiting a prior issue, I think we are still getting the post close price in the 15 minutes of late trading. If it would be possible to get the actual close that would be better. But if that is not possible we can continue to use that "almost closing price". Since you are now 100% barchart does that open up the possibility of a rebook at that question that arose before? And is there an easy way to get to the exact published closing price? No big deal if not easy...but thought I'd ask.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/3/23 9:44 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Price updates (Issue #153)


Thanks for letting me know. I’ll fix it soon.

Sent from my iPad

On Oct 3, 2023, at 7:42 AM, KelleyDrake ***@***.***> wrote:

﻿

I noticed this morning that our harvest price for corn is $4.76. Friday's 9/29 close was $4.7675 and yesterday's 10/2 close was $4.8875.
The date shown for the recent harvest price was 9/29. So it looks like last night's price update did not take effect?

**Comment by KelleyDrake** [comment]
Ok.  Thanks!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/3/23 10:01 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Price updates (Issue #153)


No, the live server isn’t using the barchart script yet. I wanted to test it on my local machine first, but couldn’t do that until last night. I did do some work over the weekend on the live server scripts to enable email notifications. That’s most likely what broke the script this morning.

Sent from my iPad

On Oct 3, 2023, at 7:54 AM, KelleyDrake ***@***.***> wrote:

﻿

Also, Ideally we would get the actual closing price. Revisiting a prior issue, I think we are still getting the post close price in the 15 minutes of late trading. If it would be possible to get the actual close that would be better. But if that is not possible we can continue to use that "almost closing price". Since you are now 100% barchart does that open up the possibility of a rebook at that question that arose before? And is there an easy way to get to the exact published closing price? No big deal if not easy...but thought I'd ask.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/3/23 9:44 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Price updates (Issue #153)


Thanks for letting me know. I’ll fix it soon.

Sent from my iPad

On Oct 3, 2023, at 7:42 AM, KelleyDrake ***@***.***> wrote:

﻿

I noticed this morning that our harvest price for corn is $4.76. Friday's 9/29 close was $4.7675 and yesterday's 10/2 close was $4.8875.
The date shown for the recent harvest price was 9/29. So it looks like last night's price update did not take effect?

**Comment by ddrake** [comment]
The new price script ran on the live server today so I'm closing this.  I'll keep an eye on prices for a couple more days, though.
