### ISSUE TITLE
Can we adjust yields mid year and before marking as final, and have that reduced yield be reflected in reduced costs

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#174]

**Comment by ddrake** [comment]
Previously, in the computation for yield adjustment fraction, we used (1 - yield factor) for the farm budget crop if yields were not set as final.  If yields were final, we computed an effective yield factor as (non-sensitized) farm_yield / baseline_yield and used (1 - effective yield factor).

To get the desired behavior, we simply always use an effective yield factor:
sens_farm_expected_yield(yf) / baseline_yield,
where the method sens_farm_expected_yield returns farm_yield if yields are final, otherwise farm_yield * yf.

**Comment by ddrake** [comment]
If this update is accepted, I'll need to update the expected values for a couple of budget tests: yf=.8, pf=.8 and yf=.7, pf=.7

**Comment by ddrake** [comment]
Update is complete in commit: a579171
I'll leave this open until manual testing is complete.

**Comment by KelleyDrake** [comment]
I see the results coming through.   Excellent!
