### ISSUE TITLE
Model Date allows future values

### ISSUE THREAD

**Issue by bemdrake** [ddrake/Integrated_Farm_Budget_Tool#18]
When creating a new crop year, it allows for the model run date to input a future date, which would include unobtainable data. This should entry should be limited by date constraint that prevents future dates and backdating too far.

**Comment by ddrake** [comment]
Fixed now.  The model run date can't be before Jan 11 of the crop year or later than tomorrow.  Users in different timezones make this slight bit of future travel necessary.  At this point I don't see an issue with that because if prices don't exist for a particular date, the application uses the most recent date that does have prices.
