### ISSUE TITLE
Consider adding a blog component

### ISSUE THREAD

**Issue by ddrake** [ddrake/Integrated_Farm_Budget_Tool#192]
As it stands, no one will ever find ifbt.farm by searching Google, Bing, etc.. because the site has only a few public pages, which rarely change.  Maybe that's OK, and people will find out about the app other ways.  SEO is sort of a scam imo, with people falling over each other and spending big $ to temporarily push up their rankings using AI and other tricks.  If we do start to care about SEO at some point, a blog with reasonably frequent posts (e.g. monthly) would help.  This might also give @KelleyDrake an easy way to discuss current market events in the context of IFBT without having to create a video each time, or to mirror video content in a textual form.  If we do this, we should also add a [sitemap](https://docs.djangoproject.com/en/4.2/ref/contrib/sitemaps/), start serving a robots.txt file, go through the process at google to get the site ranked, etc.

**Comment by KelleyDrake** [comment]
I wanna be a social media star!  Influencer!  If it drives traffic to IFBT let's do it!

Thinkint we should also advertise on the dating website farmersonly.com.  :)

**Comment by KelleyDrake** [comment]
I was actually thinking about another avenue to potentially drive both credibility and views.   Was thinking we might be able to publish in a relevant ag journal.    Looks like the main one is farm journal.  But they are for profit media outlet writing their own stuff etc.   Might be others though that would publish an IFBT writup?



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: ***@***.***
Date: 11/4/23 12:46 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>, ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [ddrake/Integrated_Farm_Budget_Tool] Consider adding a blog component (Issue #192)

I wanna be a social media star!  Influencer!  If it drives traffic to IFBT let's do it!

Thinkint we should also advertise on the dating website farmersonly.com.  :)





Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
From: Dow Drake ***@***.***>
Date: 11/4/23 12:17 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Mention ***@***.***>
Subject: [ddrake/Integrated_Farm_Budget_Tool] Consider adding a blog component (Issue #192)


As it stands, no one will ever find ifbt.farm by searching Google, Bing, etc.. because the site has only a few public pages, which rarely change. Maybe that's OK, and people will find out about the app other ways. SEO is sort of a scam imo, with people falling over each other and spending big $ to temporarily push up their rankings using AI and other tricks. If we do start to care about SEO at some point, a blog with reasonably frequent posts (e.g. monthly) would help. This might also give @KelleyDrake<https://github.com/KelleyDrake> an easy way to discuss current market events in the context of IFBT without having to create a video each time, or to mirror video content in a textual form. If we do this, we should also add a sitemap<https://docs.djangoproject.com/en/4.2/ref/contrib/sitemaps/>, start serving a robots.txt file, go through the process at google to get the site ranked, etc.

**Comment by ddrake** [comment]
This is complete in commit 016e251
