### ISSUE TITLE
MYA prices from Wasde not updated yet

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#195]
It may simply be that IFBT has not yet picked up the new Wasde data from yesterday's release.   But as of this morning the MYA estimates are still showing last October's Wasde numbers.   For November, Wheat declined by 10c from $7.30 to $7.20.  Corn declined by 10c from $4.95 to $4.85.  Beans stayed flat at $12.90.

**Comment by ddrake** [comment]
The script always been scheduled to run on the 10th, 11th, 12th and 13th.  It should run at 12:05 CT today.  The release date given in the simplebudgettool for this report is 11/11/2023 and there are no release dates for any month on the 9th.

I can change the script so it runs on the 9th as well if you like.  How about the 8th? Maybe it makes sense to have the script just ignore the release dates imported from the simplebudgettool, and run on each of the 8th-13th.

**Comment by ddrake** [comment]
I simplified the generated update script so that, while it still uses the wasde_release_date column, it ignores the _day part_ of that date.  It finds the _unique_ wasde_release_date corresponding to the month and year of the date when the script is run (and the specified cropyear).  It then updates prices for records in that crop year with dates greater or equal to the found wasde_release_date.

I changed the schedule so that going forward, the script runs each day in the range: 8th - 13th at 12:05 CT.  If the server response to the request for the wasde file contains "This file is not yet available", the script simply exits without generating or applying any updates.

Complete in scripts_ifbt commit [22de5b2](https://github.com/ddrake/scripts_ifbt/commit/22de5b2bdc17095940b454d271804cc45a7375ac)
