### ISSUE TITLE
Server error when I unlocked the manual date and then ran a sensitivity analysis or a budget

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#247]
Not sure if you saw the Server error message yet.   But had an odd one come up today on my Riley Kansas farm.   All was working fine until I went from a manual date of 3/15/24 to turning that off.   I then got server errors on both budgets and sensitivities.   It was right at the end of my presentation so it did not cause any major problems.    But hoping you can take a look at that.   Thanks!

**Comment by ddrake** [comment]
This was an edge case.  It occurred on Monday June 3 before 1 pm PT.  Since wheat was "in discovery", the code tried to pull the average discovery price from the database for June, but there were no prices for June yet.  This sort of issue should be resolved once we update to use the RSS feed from the RMA for discovery prices.
