### ISSUE TITLE
Get running updates on price volatility and projected price during the discovery period

### ISSUE THREAD

**Issue by ddrake** [ddrake/Integrated_Farm_Budget_Tool#6]
We can get data here: https://prodwebnlb.rma.usda.gov/apps/PriceDiscovery/GetPrices/YourPrice that will give us running updates during discovery.  If we could access the underlying data set and/or formulas, we wouldn't have to ask the user for these values and/or could provide more accurate default values.

**Comment by ddrake** [comment]
We're not asking the user for these values anymore.  In the initial version, we use the previous year's price volatility and the current futures price.  This refinement is still planned for implementation.

**Comment by ddrake** [comment]
Currently, in the period from the beginning of the year to March 1 (i.e. before the RMA has released price volatility and projected price data for all counties), we simply use the previous year's price volatility factor and the current futures harvest price as estimates. This could be improved as follows:

Once we know the formulas and can get access to the data sources, we could easily calculate on a daily basis the “rolling” weekly volatility factors and also the rolling projected harvest prices (just like the RMA does in their tool). The price volatility factors would derive from the options markets and the projected price would derive from harvest futures prices. The application would compute and store these values each day, thus permitting "time travel" back to Jan 1, in which premiums and indemnities could be based on those early estimates.

**Comment by ddrake** [comment]
https://www.barchart.com/futures/quotes/ZCZ23

I think this is where RMA gets the daily Implied volatilities that they flow into their model.

**Comment by KelleyDrake** [comment]
https://legacy.rma.usda.gov/pubs/2015/volatilitymethodology.pdf
This PDF shows how to convert the daily volatility factors from Barchart.com into an RMA daily volatility factor.   As noted in this PDF, the last 5 days of RMA daily volatility factors are averaged and rounded to produce the final volatility factor used for Crop insurance premium calculations.   At some point down the road, I'd suggest that both prior to the start of the Projected Price discovery period and during the Projected Price discovery period we replicate the RMA calculation for the prior 5 trading days and use that average as our estimate of Volatility Factor for crop insurance premiums (instead of prior year's volatility)   For Projected Prices, up to the start of the discovery period we use the appropriate harvest futures contract price as our proxy for Projected Price.   No change suggested there.   But once the discovery period starts, I think we should start creating a rolling average to estimate the ultimate Projected Harvest price as further described.   If, for example, there are a total of 20 closing prices that will be used to calculate the Projected Harvest Price for corn in one region.   And the first five days closes are $5.50, $5.40, $5.30, $5.20 and $5.10, then I suggest we calculate the expected Projected Price as of that date as follows:   We take the average of the first 5 observations ($5.30 in this instance) x 5 Plus the last observation $5.10 x the 15 remaining unknown closing prices and divide by 20.   So in this example: (($5,30 x 5) +($5.10 x 15))/20 = ($26.50+$76,50)/20 = $103/20 = $5.15.   This assumes that the last day's closing price is the best estimate for the remaining 15 unknown closing prices.   The next day will have six actuals and 14 unknowns with the 14 unknowns plugged as the latest closing price.   At the end of the Discovery Period, all of the 20 required closing prices will be known and our calculation should match the RMA's final number.   Using the average of the last 5 days RMA volatility factors on any given date will give the best estimate at any point in time of the final volatility factor.   The weighted average calculation described above should provide the best possible estimate of the Projected Price and will converge to the final RMA "locked" price.   This approach should also be used on discovered Harvest Price) at any point in time during the Discovery periods.    Our current assumption of prior year volatility and harvest price are good for now.   But down the road this refinement would make our estimates both prior to and during the discovery period considerably more timely and accurate.

**Comment by ddrake** [comment]
@KelleyDrake: Do we have all the price data we need to implement this?  Also, your example of the calculations is clear, but I couldn’t remember if you had a tab for it in the simple budget tool workbook.

**Comment by KelleyDrake** [comment]
This is an aspirational enhancement that will require some new data and logic..if we choose to implement it.   To do these calculations the way that RMA does for prices they take the observed closing prices for those days falling within the discovery period and take a straight average. They then round them and show that to the user as the in discovery price.   I think there is a better way to do this to get to a closer ultimate answer than the RMA.   Assuming there were 20 calendar trading days in a price discovery period, and let's say you just completed the 8th day, what I would do is take the 8 day average (weighted by 8/20) and then take the last trading day price (weighted by 12/20) to get to an estimated discovered price.   This assumes that the 8th day is the best available predictor of the remaining 12 days.    The RMA does not do this.   They use the 8 day average as their "in discovery" projected price.   My version makes more sense to me.    Today we simply use harvest price daily close as out rolling projected price prior to and  during discovery.  RMA's approach would be better than ours.  And my weighted average approach during the discovery period would be better than RMA. Volatility factor is another kettle of fish.   The RMA does not calculate or report a rolling Volatility Factor.   That is calculated and reported using the implied Volatility of the final 5 days of the discovery period.   There is a formula to calculate this that the RMA uses that relies on a calculation of observed Volatility in the futures prices as derived from options pricing. With some work we could probably replicate the RMA's calculations.   And on any given day prior to or during the discovery period, we could calculate the Volatility factor.  I saw the RMA calculation once and we could probably find that and replicate it.  We'd need to also gather the underlying Volatility data from Barchart that is used in the calculations.

Both projected price (however we decide to do it) and Volatility would change from day to day just like prices.   So if we wanted to time travel, we'd have to go back and look up and compute the averages and also look up, grab and comoute the Volatility.  Right now we simply use last year's Volatility factor until the final Vol factor is reported by RMA.

This probably is all doable but we should probably discuss whether the juice is worth the squeeze.   It would be a nice relatively small value added enhancement.   Might be fun challenge to see if we could do it.   But maybe also not worth the effort?

**Comment by ddrake** [comment]
We can talk about this over the phone.  I just think we should take another look at it for possible implementation this fall.  I'm fine with either your algorithm or the RMA's, whatever you think will give the best estimates to projected price and price volatility factor both before and during the price discovery period.  It would definitely support time travel by computing based on the model run date.

I'm still not clear if we have all the prices we would need to estimate projected price.   Also, I'm not sure even what sort of data goes into the volatility calculations -- some kind of options prices, right?

**Comment by KelleyDrake** [comment]
I think we do pull down all the necessary futures prices but we'd need to save a series of daily data in order to calculate the averages.

We definitely would need options volatility data from barchart.  I'd need to go back and replicate the RMA calculation to be sure how and which volatility factors are used and manipiulated by RMA to get to their pubkished Vol.   I dont remember if the Vols they use are only for those harvest price futures that are used for price diacovery or whether they use volatility factors for more than one futures month.   I think that the daily volatility factors are accessible on Barchart and  visible and downloadable to the user -- but would need to confirm that.  We'd have to figure out the "ticker" equivalent for the daily volatility(ies) for every harvest contract in order to grab that data from Barchart.   My recollection is that the RMA takes those barchart inputs and then makes a few adjustments to get to their Vol numbers.   Let's talk on Monday about next steps if we decide to tackle this enhancement

**Comment by ddrake** [comment]
Sounds good!

**Comment by ddrake** [comment]
The RMA’s calculations are pretty straightforward.      I think the challenge will be getting access to a series of historical volatility data. 

Barchart does have a free trial for their PREMIER Barchart subscription and if we do need it on an ongoing basis it is $16.67/month.   Barchart does have a 30 day free trial for their Premier subscription.   So we could try that out to see if we can get the daily volatilities historically for 2023 crop year discovery periods.     

If, however, we want to do the volatility calculations for the 2024 crop year and beyond, then I think that Barchart publishes the volatility figure for each contract for every trading day that we could scrape and save.   See the screen shot below :  Volatility & Greeks” for Dec 24 corn.   You’ll see in the table the Implied Volatility of 19.69%.

By early January 2024  (opening date for IFBT 2024), all of the winter wheat crops discovered prices and volatilities would already be finalized (and we would have accessed those from the RMA).   So for purposes of the volatility calculations, we’d need to concern ourselves with only the Spring planted wheat, corn and soybeans.     Here are the contract volatilities that we’d need.

Corn
For Corn everything uses the December CBOT contract with the exception of part of Texas which uses the September CBOT contract. 

Soybeans:
For Soybeans two contracts are used, the November CBOT contract and the January CBOT contract.

Spring Wheat:
Spring Wheat uses MGEX September HRS Contract for all areas except NV and UT.   NV and UT Spring Wheat uses CBOT September SRW Contract for Projected Price.  Fyi.. although it does not impact volatility, they use Portland Merchants Exchange SRW for Harvest Price calculation.

So if we wanted to produce daily rolling five day average volatility calculations for the Spring Planted crops for the 2024 year, we’d need to start capturing and scraping daily volatility data starting at least a week prior to opening of IFBT in early January (perhaps in December 2023 to be safe and test results).

The tickers for the 6 contracts, the contract description and date, and the latest volatility reading are as follows:

ZCZ24                   CBOT Corn Dec 24                                         19.45%
ZCU24                  CBOT Corn Sep 24                                          20.70%
ZSX24                   CBOT Soybeans Nov 24                                16.86%
ZSF25                    CBOT Soybeans Jan 25                                  No Options Available Yet on this Contract
MWU24               MGEX Spring Wheat Sep 24                        18.10%
ZWU24                 CBOT Spring Wheat Sep 24                         26.48%

If we wanted to be able to “time travel” through the 2023 crop year we’d need the historical volatility data.    And it would be good to have some historical 2023 data on volatility to be sure that we can replicate the RMA’s calculations and confirm that the way we are doing them matches the RMA.    But I think we might either need to use the free trial to get that historical volatility data by contract -- or else buy the Barchart Premiere to get it on an ongoing basis.   Maybe we could do the free trial to try to see if we could get the historical series of volatilities from Barchart (and then save those and use those retrospectively for the Spring planted crops for the 2023 crop year).   If we could get that historical data, we could replicate the RMA volatilities using their formulas.    And once we proved that out, perhaps going forward, we could dump the free trial and instead just scrape the volatilities for the 6 contracts we need on a go forward basis?    We can discuss Monday.

As it relates to the weighted average projected prices and harvest prices during the discovery periods, we know and have documented the Projected Price discovery date ranges and the Harvest Price discovery date ranges for each crop and region.   And we are already capturing all the relevant price data.    So up until the first day of the discovery period we would use the relevant harvest futures price.  Then during the harvest price discovery period we’d use the weighted average calculation.  To do the math correctly we’d need to count up the number of trading days in every Spring planted crop individual spring and harvest price discovery period (taking into account trading days, weekend and holidays, etc). 

 I looked back at a few of discovery periods and it looks like they typically have 19 -22 observations.   I think it would not be too hard to go through each projected price discovery period and each harvest price discovery period for each of corn, wheat and beans in every region and carefully count up the 2024 trading days in each period eliminating holidays and weekends -- and then code those into the model.    Because of calendar shifts, every year would have different total number of trading days in the calculation.   So that would be an ongoing data entry calculation for each crop year going forward. 

If we didn’t want to go through that brain damage, we might instead also consider a simplifying assumption that all periods had, for example, 20 trading days and do our weighted averages on that basis.    That would add some complexity and inaccuracy in the weighted average calculations in short periods (eg. 18 days) and long period (eg. 22 days).   So maybe better to just spend the time and add up and code the actual trading days for each discovery period.  We can discuss.
I did some work to help identify how many days there would be in the weighted average discovered prices calculations.   It was impossible to understand the CME’s holiday schedule and it did not go out to 2025.   However, the NY Stock Exchange schedule is easy to understand and use.   I’m making the assumption that commodity futures have the same holidays (and therefore no closing prices) as the NYSE.   I think it is a pretty reasonable assumption.    So for each unique price discovery period, I took into account weekends and holidays and excluded those days to get to the number of trading days that would show up in the RMA’s averages.   For the 2024 crop year they range from 19 to 23 days.   I’d want to reconfirm everything but have a framework set up.   Note that I checked that leap years include February 29 (if it is not a holiday or weekend) in the calculations – and 2024 is a leap year.  

I also did an example of what the rolling volatility calculation might look like.  So, for example, if we were live for 2024 crop year now (which we are not), I show what that calculation would look like for Corn with a February Projected Price discovery period and an October Harvest Price discovery period.    I input last Friday’s volatility from Barchart and then made up placeholder numbers for the next 4 trading days.   I then complete the steps in the RMA’s calculations.  

Visualizing these is helpful to me.   I uploaded the spreadsheet to IFBT.Farm share site.

**Comment by ddrake** [comment]
In our meeting today, we decided to just play around with this, and not try to implement it for 2024

**Comment by ddrake** [comment]
Perhaps we take an easier path and do exactly what the RMA does…and simply take the straight average of the actual closes to date and use that as the discovered spring projected and fall harvest price estimate until that goes final?   Is that something that would be hard to do from a programing perspective?    I think we still don’t try to tackle the volatility calculation problem yet and push that out to a later date.

- Prior to discovery we use harvest price
- During discovery we use straight average of actuals to date within discovery period
- And at the end of discovery we use the final discovered price from RMA

This would apply to both projected price discovery and harvest price discovery.

**Comment by ddrake** [comment]
Complete in commit: 0f7fe4a
