### ISSUE TITLE
Crop Insurance Not Working

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#81]
I created a new test farm called Demo.  I used the manual date setting to put it back in time to 1/15/2023.    I set corn and beans and wheat to an 80% RP policy and ran the model, which produced a $77k total crop insurance bill and a $157k total pre-tax cash flow.   I then changed the corn and bean policy to 85% RP.   It did not change the crop insurance number in the model or the total pre-tax cash flows.

**Comment by ddrake** [comment]
Fixed in commits: [b815b5b](https://github.com/ddrake/Integrated_Farm_Budget_Tool/commit/b815b5ba11bd54bc578bffc248e243dbab745fde) and [c05c64cf](https://github.com/ddrake/Integrated_Farm_Budget_Tool/commit/c05c64cf779a161d8f9792e966266f182fd87d51)
This bug was due to an index miscalculation in getting the selected premiums from the pre-computed nested list.
