### ISSUE TITLE
Test of Crop Insurance Premium Produced Different Results than RMA

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#83]
On my Demo farm, I planted 600 acres of non-irrigated corn in Summit County, Ohio.   I insured that in IFBT at the 85% level with a 180  TA APH yield, 165 Rate Yield and 165 Adjusted Yield.   I selected TA and YE in IFBT.  That produced a premium cost per acre of $65/acre.  That seemed quite high to me so I thought I would doublecheck that against the RMA premium calculator.

I put those same inputs into the RMA premium price calculator and it resulted in $33,517 of producer paid premium which when divided by 600 acres equals $55.86/acre.     FYI, the RMA tool allows for QL, TA, YA, YC (and not YE).   I first used TA only and got $33,517.   Then I added YA also and got the same $33,517 number.

I'm not sure what explains the approximately $9/acre difference in the two calculations.  I may be doing something wrong.  But I would have expected IFBT premium to match the RMA calculator premium.

https://ewebapp.rma.usda.gov/apps/CostEstimator/Estimates/DetailedEstimateQuote.aspx?EstimateId=844653

**Comment by KelleyDrake** [comment]
I think I know the answer!  I was time traveling to January 15, 2023 for this.   Recall we were using last year's (2022) volatility factor and the then current harvest price as best estimate of Projected Price.   The actual final discovered ones in the RMA tool are $5.81 Projected price and .18 Volatility factor.   I think that as of Jan 15, 2023 we were using the then current harvest futures price of $5.985 (a little higher than what proved to be the final Projected Price) and the 2022 volatility factor which was .23 (considerably higher than the .18 that it turned out to be).   So on January 15, 2023, our use of the higher Projected Price and the higher Volatility factors were undoubtedly responsible for the differences in the premium calculations.

**Comment by KelleyDrake** [comment]
I think I spoke too soon.    I thought I'd test the hypothesis in my last post.   Turns out that I may NOT know the answer.  I time traveled forward to 4/1/2023 to a time in which Projected Price and Volatility factors should have been locked at .18 and $5.81.   I thought I would see the corn crop insurance premium in IFBT drop from $65/acre to $56/acre.   But it did not do that.   IFBT stayed at the same $65/acre crop insurance number.   That tells me that time travel may not be working for Crop Insurance?   I would have thought by rolling forward the clock to after the discovery period, that crop insurance premiums would change for sure.   And since final Projected Price and Volatility factors were lower than what we were using on 1/15/23, then I would have expected the crop insurance premiums to be lower on 4/1/23 than on 1/15/23.

**Comment by ddrake** [comment]
Thanks!

We are caching premiums for performance, but there was an issue with the way I was managing the cached premiums.  The cache premiums for farm crops weren't getting invalidated when the model run date changed in the farm year.

I believe this is working now per commit 4e942f2.

________________________________

**Comment by KelleyDrake** [comment]
Dow,

Yes.   Your changes definitely helped.

I just tested the crop insurance premium.   The time travel does appear to now be working.   Here are the results.  They do raise a couple of questions though which are summarized below.

I used the same Summit County OH assumptions as before: 600 acres of corn, enterprise, non-irrigated, 85% RP, Rate 165, Adj 165, TA APH 180, Risk no, TA yes, YE yes
On 1/13 futures price was $5.985 and our Volatility from prior year was .23, I get $65/acre premium from IFBT
On 2/24 futures price was $5.7625 and our Volatility from prior year was .23, I get $65/acre premium from IFBT

That would suggest that the 22c decline in corn price did not change the premium.  I’m not sure how sensitive premium prices are to Projected Price but was a little surprised not to see that premium move at all despite a 3.7% decline in estimated Projected Price.

When I ran IFBT on 3/3, the futures price was $5.71 but since it has crossed over to Discovered and locked, I presume on that date we are now using the final discovered $5.91 discovered price and the .18 final volatility factors.
I get a $58/acre premium.   So that $7/acre drop in premium makes sense due to the large drop in Volatility factor.

I do want to note that using the same input information in the RMA tool, I get a $56/acre premium or $2/acre less than the $58/acre we are coming up with.

So my questions are:

  1.  Should the change in harvest price prior to the Price discovery date going final change the calculation for premium – or does Projected Price not have a strong enough effect on premiums to move them off of $65/acre.
  2.  It would be good to reconcile to the RMA tool.   After the end of the Discovery Period, we have a pretty minor $2/acre difference.   But I wonder what causes that difference?

I will work with the RMA tool a little more to see if I can exactly reconcile RMA to IFBT.  Perhaps you can take a look and see if you come up with the same minor $2/acre inconsistency?

Also not sure if there are any tests you can do on your end to see whether the changing harvest prices prior to final discovery are, in fact, going through the model.    And, if they are, does seem correct that the 3.7% price decline don’t “move the needle” enough to change the premium calculation off of $65/acre.

All of this can wait until for whenever we get to it.   Since this was more of discussion that issue per se, I thought I’d run it past you in e-mail first to decide whether or not to put it up on the “Issues List”.

**Comment by ddrake** [comment]
The cache invalidation logic became too complicated (too many unforeseen edge cases creating coupling between farm year and farm crop) so I removed the caching of premiums -- except indirectly in the context of the sensitivity table so the premiums should now always be computed correctly regardless of any changes to the model run date.  

I modified the sensitivity code so it computes the (non-sensitized) total nonland cost (which requires premiums to be computed) once for each farm crop, storing those values.  It then passes these values to the total cost function each time the (sensitized) total cost function is called for a crop.  There is some slowdown, but the code will be much easier to maintain going forward.

I still think that implementing #42 will give much better performance.   But I have to have tests #77 in place before I can start on that.

The post discovery difference between the application premiums and the ones from the RMA site might also have been caused by the caching issues; it seems unlikely, but it might be worth checking it again now that the caching is removed.  I think it's important to resolve that $2 difference.  

I'm not very adept with the RMA tool, but I think it generates a worksheet with intermediate calculations (although the order of computations different).  Maybe that could be helpful in resolving this test case.  We also have the [Enterprise Premiums](https://docs.google.com/spreadsheets/d/1Uy-30HtWAFNabmfgvFjdlueej0xjuZLU/edit?usp=drive_link) spreadsheet.  I could make a copy of that and fill in intermediate values from the premium computation if that would be helpful.

**Comment by ddrake** [comment]
There were two errors in the premium code which resulted in our premiums being about 4% too high in some cases.  Fixed in commit 0d85893  
- An adjustment for YE was being made to the interpolated rate_differential_factor, but this should not be done for the Enterprise unit
- The Min() calculations in step 3.05 of the worksheet were not implemented.  This was responsible for most of the error.

After making these updates, the correct producer premium amount ($33516.64 or $55.86/acre) was computed.

Steps 3.07, 3.08 (marginal rate adjustment factor) and 5 (historical capping) are not being computed by the current code.  In the context of this test case, these omissions didn't affect the premiums, but this logic should be added.  These items are likely to take a bit of time, and the historical capping may require additional RMA data to be added to the database so these items have been added to a new issue #96
