### ISSUE TITLE
Price not updating and are not equaling closes

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#99]
I went back to my Marquis Farm today.   Today is Wednesday 7/12, so I had anticipated that futures prices would have been updated to yesterday's close on Tuesday 7/11.   Instead, when I go to the marketing tab, it tells me that prices were updated as of 7/7 or Friday of last week.  

Also (and this is a bit of a strange one), the numbers shown for 7/7 harvest prices are not the exact numbers as the actual closing prices for that date.   IFBT is showing 7/11 close for Corn of $4.96, Beans of $13.19 and Wheat of $6.52.   But when I go out to Barchart and Yahoo, I get closing prices for Corn of $4.945 (rounds to $4.95, Beans $13.1775 (rounds to $13.18) and Wheat $6.495 (rounds to $6.50).   

So it appears that the updating process is not happening automatically and also there is some very slight variation from the closing prices shown in IFBT vs the actual closing prices (as shown in Yahoo and Barchart which both have identical closing numbers)

**Comment by ddrake** [comment]
Currently all the nightly scripts are stored and scheduled running on my local machine.  This makes it easier for me to monitor the scripts' behaviors and modify them to handle unexpected issues and also to ensure that my development database is "in sync" with the server database with respect to external data which is updated/inserted by nightly scripts. 

Eventually all the scripts that affect the live server database will be moved to the server and scheduled there  See issue #101.  The script to backup the live server database will be performed both locally and at the server.
The price inserts failed the last couple of days because my laptop, which has very low battery capacity, and which I normally keep on external power, shut itself down both nights without my knowledge.  The scripts should run tonight around 8pm PT and automatically fill in all the missing prices.

Regarding price *differences*, We're downloading closing prices at around 8PM PT (well after the market closes).  In your example of ZCZ23 on 7/7, at 8PM PT, we downloaded the price 4.965.  When I go there now, I see 4.945, matching the value you saw.  However the 7/6 price in our database does match the one in Yahoo.

I think sometimes the closing price is adjusted; it's not stated when adjustments are made.   I currently have no provision to update futures prices, but only to insert them.  It will take some time, but I can add updates, say for the past week, to update prices that may have been adjusted after they were downloaded and inserted.  I'll leave this issue open until that is complete.

**Comment by KelleyDrake** [comment]
One possible reason for the difference in prices is that I think the futures markets reopen after the market close and trade in an overnight session.   That could be the cause of the issue?   Once known and final the market close won’t change.  But if we are pulling down an overnight trading price, that might be causing the difference.  Just one possible explanation?

These contracts will trade on the CBOT's electronic platform from 6:30 p.m. to 6:00 a.m. and 9:30 a.m. to 1:15 p.m. (Chicago Time).

**Comment by ddrake** [comment]
I added and tested the update feature mentioned above so that going forward, the databases will be updated to reflect any adjustments to posted futures prices made within a week of the priced_on date.
